### ISSUE TITLE
Edit and execute command in editor

### ISSUE THREAD

**Issue by sbeldekov** [rcaloras/bash-preexec#63] opened 2017-12-21 11:09 UTC
Bash -4.4

1) press C-X,C-V to open an editor (vim in my case) and edit a command (e.g. 'uptime'), save and quit
2) see the following output

`$ `
`uptime`
`__bp_preexec_invoke_exec "$_"`
`14:00  up 12:18, 2 users, load averages: 1.44 1.56 1.58`

I believe the 3rd row is unwanted

Thanks!

**Comment by rcaloras** [comment] 2017-12-21 18:59
@sbeldekov thanks for opening! This issue was originally opened and closed back in April. Check out the full thread: https://github.com/rcaloras/bash-preexec/issues/36 

This is intended functionality with edit and execute. Closing since it's a duplicate of the other issue. Feel free to reopen if you feel differently.

**Closed by rcaloras** 2017-12-21 18:59 UTC
